---
- name: Ensure that firewalld is installed and enabled
  hosts: node[1:3]
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure that firewalld is installed
      yum:
        name: firewalld
        state: installed
      check_mode: on
    - name: Ensure that firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes
      check_mode: on

- name: Ensure that firewalld is configured for proxy
  hosts: node1
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure port 8080 is permitted to HAProxy
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
      check_mode: on

- name: Ensure that firewalld is configured for web nodes
  hosts: node[2:3]
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure port 9080 is permitted to Web nodes
      firewalld:
        port: 9080/tcp
        permanent: yes
        state: enabled
      check_mode: on
