---
- name: Ensure SELinux is enabled and configured
  hosts: node[1:3]
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure that SELinux is enforcing
      selinux:
        policy: targeted
        state: enforcing
