- hosts: node3
  become: yes
  vars:
    nginx_vhosts: 
      - listen: "443 ssl http2"
        server_name: "node3.rhdemo.io"
        server_name_redirect: "www.node3.rhdemo.io"
        root: "/var/www/node3.rhdemo.io"
        index: "index.php index.html index.htm"
        error_page: ""
        access_log: ""
        error_log: ""
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "node3.rhdemo.io.conf"
        extra_parameters: |
          ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
          ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;


      - listen: "80"
        server_name: "node3.rhdemo.io www.node3.rhdemo.io"
        return: "301 https://node3.rhdemo.ios$request_uri"
        filename: "node3.rhdemo.io.80.conf"        

  roles:
    - role: geerlingguy.nginx
