---

- name: ENSURE LOCAL USERS EXIST
  hosts: all
  gather_facts: no
  tags: create_user
  become: yes
  
  tasks:

    - set_fact:
        test_pass: "{{ user_password | password_hash('sha512', 'mysecretsalt') }}"
        
    - name: CREATE LOCAL USERS
      user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: wheel
        append: yes
        update_password: always
        password: "{{ test_pass  }}"
        create_home: yes
      loop:
        - rick
        - morty

    - debug:
        msg:  "{{ test_pass }}"
    
        

- name: UPDATE THE PASSWORDS ON ALL SYSTEMS
  hosts: all
  gather_facts: no
  tags: update_pass
  become: yes
  
  tasks:

    - set_fact:
        test_pass: "{{ user_password | password_hash('sha512', 'mysecretsalt') }}"


    - name: CHANGE THE PASSWORD
      user:
        name: "{{ user_name  }}"
        update_password: always
        password: "{{ test_pass }}"
