---

- name: ENSURE LOCAL USERS EXIST
  hosts: all
  gather_facts: no
  tags: create_user
  become: yes
  
  tasks:
    - name: CREATE LOCAL USERS
      user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: wheel
        append: yes
        update_password: on_create
        password: test123
      loop:
        - rick
        - morty

    
        

- name: UPDATE THE PASSWORDS ON ALL SYSTEMS
  hosts: all
  gather_facts: no
  tags: update_pass
  become: yes
  
  tasks:

    - name: CHANGE THE PASSWORD
      user:
        name:
          name: "{{ user_name }}"
          update_password: always
          password: "{{ user_password }}"
