---
- name: Gather host facts
  hosts: web
  become: yes
  
  tasks:
    - name: Report
      debug:
        msg: "Facts gathered for {{ inventory_hostname }}"

- name: build report with facts
  hosts: ansible
  
  tasks:

    - name: build a report
      include_role:
        name: build_report
