---
- name: Gather host facts
  hosts: all
  become: yes
  
  tasks:
    - name: Report
      debug:
        msg: "Facts gathered for {{ inventory_hostname }}"

# - name: build report with facts
#   hosts: localhost
#   gather_facts: no

#   tasks:

#     - name: build a report
#       include_role:
#         name: build_report
