---
- name: DEMONSTRATE THE REBOOT OF A SYSTEM
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Patch the server
      debug:
        msg: "Patching completed for {{inventory_hostname}}"
        
    - name: Collect uptime before reboot
      command: uptime
      register: output
      
    - debug:
        var: output.stdout
      
    - name: Reboot each server
      reboot:
        test_command: uptime
      register: output

    - name: Collect uptime after reboot
      command: uptime
      register: output
      
    - debug:
        var: output.stdout
