---
- name: DEMONSTRATE THE REBOOT OF A SYSTEM
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Display uptime before reboot
      command: uptime
      register: output
      
    - debug:
        var: output
      
    - name: Reboot each server
      reboot:
        test_command: uptime
      register: output

    - debug:
        var: output
